version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    restart: always
    container_name: my-headless-project-wordpress
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    container_name: my-headless-project-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  astro:
    build:
      context: .
      dockerfile: Dockerfile.astro
    container_name: my-headless-project-astro
    ports:
      - "4321:4321"
    volumes:
      - ./astro-project:/app/astro-project
    depends_on:
      - wordpress

volumes:
  db:
  wordpress:
  astro_project:
