# Use the official WordPress image as a base
FROM wordpress:latest

# Install WP-CLI
RUN apt-get update && \
    apt-get install -y less mariadb-client && \
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp


# Add a non-root user
RUN useradd -ms /bin/bash wordpress
USER wordpress
